server:
  port: 9090

rabbitmq:
  host: b2d2bb80e0f843e396337084925a54fc
  port: 5672
  username: ea91066a691544fd98109e8eb7e6a494
  password: ff39e7234e55400ebf81feec38e1b64e

# NHN SecureManager
secure-key-manager:
  url: https://api-keymanager.cloud.toast.com
  app-key: mcXcTmrnbRezlila
  local-key: gaship
  user-info-protection-key: 8174a0ef88454634911b8aa84988ae12

log-crash:
  project-name: ba486da0545d4479a267976ee3ad4821

logging:
  level:
    root: info

aes:
  algorithm: AES/ECB/PKCS5Padding

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true

  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true #재시도
          initial-interval: 500ms # 최초 메시지 처리 실패 후 재시도까지의 인터벌
          max-interval: 1s # 최대 재시도 인터벌
          max-attempts: 2 # 최대 재시도 횟수
          multiplier: 1 # 이전 interval * multiplier = 다음 interval

---

spring:
  config:
    activate:
      on-profile: dev

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 2016554d23614b28b1ffb17e68a0d640
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5

---

spring:
  config:
    activate:
      on-profile: prod

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 8fa7304edb474141a7197065bc5edfeb
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5
