rabbitmq:
  host: b2d2bb80e0f843e396337084925a54fc
  port: 5672
  username: ea91066a691544fd98109e8eb7e6a494
  password: ff39e7234e55400ebf81feec38e1b64e

# NHN SecureManager
secure-key-manager:
  url: https://api-keymanager.cloud.toast.com
  app-key: mcXcTmrnbRezlila
  local-key: gaship
  user-info-protection-key: 8174a0ef88454634911b8aa84988ae12

aes:
  algorithm: AES/ECB/PKCS5Padding

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  profiles:
    group:
      local: common, testdb
      dev: common, devdb
      prod: common, proddb
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 500ms
          max-interval: 1s
          max-attempts: 2
          multiplier: 1


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
datasource:
  classname: com.mysql.cj.jdbc.MysqlDataSource
  master: 2016554d23614b28b1ffb17e68a0d640
  slave : jdbc:mysql://133.186.211.156:3306/eggplant_delivery_slave
  locale: jdbc:mysql://133.186.211.156:3306/eggplant-locale
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5
server:
  port: 9090
---

spring:
  config:
    activate:
      on-profile: common

datasource:
  classname: com.mysql.cj.jdbc.MysqlDataSource
  master: 2016554d23614b28b1ffb17e68a0d640
  slave : jdbc:mysql://133.186.211.156:3306/eggplant_delivery_slave
  locale: jdbc:mysql://133.186.211.156:3306/eggplant-locale
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5

---

spring:
  config:
    activate:
      on-profile: testdb

datasource:
  classname: com.mysql.cj.jdbc.MysqlDataSource
  master: 2016554d23614b28b1ffb17e68a0d640
  slave : jdbc:mysql://133.186.211.156:3306/eggplant_delivery_slave
  locale: jdbc:mysql://133.186.211.156:3306/eggplant-locale
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5
---

spring:
  config:
    activate:
      on-profile: proddb

datasource:
  classname: com.mysql.cj.jdbc.MysqlDataSource
  master: 2016554d23614b28b1ffb17e68a0d640
  slave : jdbc:mysql://133.186.211.156:3306/eggplant_delivery_slave
  locale: jdbc:mysql://133.186.211.156:3306/eggplant-locale
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5